FROM ubuntu:16.04

COPY keys/ /tmp/keys/

RUN apt-key add /tmp/keys/xpra.org-20180504.asc && \
    echo "deb http://xpra.org/ xenial main" > /etc/apt/sources.list.d/winswitch.list 

RUN apt-get update && \
    apt-get install -q -y gosu x11-apps libgtk2.0-0 libcanberra-gtk-module xpra=2.0-r15319-1

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

ENV DISPLAY=:100

RUN printf "\
if [ -z \"\$DISPLAY\" ]; then\n\
    export DISPLAY=:100\n\
fi" >> /etc/bash.bashrc

ADD common/ /
ADD debian-series/ /
RUN chmod a+x /entrypoint.sh /preexecAsRoot.sh
ENTRYPOINT ["/entrypoint.sh"]
